### PR TITLE
listings: fix /lists/ route

### LINKED ISSUE #352: URL `/lists/` gives an error
while `/lists` is fine.

which seems to happen because the `Listing` router is defined after the `Inventory` one in `/app/init_app.js`. 

Ending up triggering [`'lists/(:id)(/)'`](https://github.com/inventaire/inventaire-client/blob/master/app/modules/listings/listings.js#L8) and not [`'lists(/)'`](https://github.com/inventaire/inventaire-client/blob/master/app/modules/inventory/inventory.js#L30)

### PR DESCRIPTION
**Pull request by maxlath**
fix #352

### CODE REVIEW

File: app/modules/listings/listings.js [hunk 1]
```diff
@@ -1,31 +1,21 @@
 import app from '#app/app'
-import { getListingMetadata, getListingPathname, getListingWithElementsById } from './lib/listings.js'
 
 export default {
   initialize () {
     const Router = Marionette.AppRouter.extend({
       appRoutes: {
-        'lists/(:id)(/)': 'showListing',
```
Comment (jum-s) [inline app/modules/listings/listings.js:8]: dont we lose access to a list by deleting this line ?

**Review by jum-s — CHANGES_REQUESTED** [review]

File: app/modules/listings/listings.js (hunk 1 above)
Comment (maxlath) [reply app/modules/listings/listings.js:8]: Indeed, that was a mistake. Fixed in the amended commit bac809abe
